### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by PavanBilagi** [kiruba-r11/Simple-Calculator#1]
Hi

I wanna contribute to your repository. Are you open to contributions?

**Comment by kiruba-r11** [comment]
Sure go ahead. The UI is ready, you may work on the code part (logic).

**Comment by PavanBilagi** [comment]
> Sure go ahead. The UI is ready, you may work on the code part (logic).

Thanks @kiruba-r11. I ll work and raise PR

**Comment by PavanBilagiHalodoc** [comment]
@kiruba-r11 This is my official email id. I'll contribute from this account. Please reassign to this account

**Comment by PavanBilagiHalodoc** [comment]
@kiruba-r11 Can you please provide proper permission? I have done some changes and unable to raise PR.

**Comment by kiruba-r11** [comment]
Join my Slack workspace for further discussion! https://join.slack.com/t/github-workspacehq/shared_invite/zt-mjior45g-2OHBAepKoQVALxYxVlPnHw

**Comment by PavanBilagiHalodoc** [comment]
Hey,

Currently, I don't have proper access to the repository and unable to
create a branch.

Can you please provide access


Thanks,
Pavan bilagi
